docs(readme): Clarify behavior around package specification
zkat/npx pull request #6
Opened 2017-05-30 10:02 UTC by stuartpb

This moves the documentation for `@<version>` suffixes to the documentation of package specification (where the version suffix logically applies).

2017-05-30 10:03 UTC, stuartpb commented
I kind of presumed the `@<version>` syntax works for tags as well, tbh if it doesn't I'd consider that a bug

2017-05-30 10:18 UTC, stuartpb commented
I put `docs(readme)` but I just realized that, since this touches usage, it has to adjust the runtime documentation as well, still pretty much a docs/readme patch though imo

2017-05-31 05:38 UTC, zkat requested changes
Hi! Thanks for this. Looks pretty good so far, pending a couple of changes. 👍

2017-05-31 05:38 UTC, zkat commented on README.md
> +`npx [--package|-p <package>[@<version>]] [--cache <path>] [--save-dev|-D] [--save-prod|-P] [--save-optional|-O] [--save-bundle|-B] [--save-exact|-E] [--global|-g] [--prefix|-C] [--userconfig <path>]
Since both `<command>` and `<package>` accept `@<version>`, I think we should document this in both.

2017-05-31 05:38 UTC, zkat commented on README.md
> +By default, `<command>` will be read from a `<package>` with the same name, which will be installed globally prior to execution. This behavior can be altered with the following options:
s/globally/to a temporary directory/

2017-05-31 05:38 UTC, zkat commented on README.md
> +* `-p, --package <package>[@<version>]` - define the package to be installed. An optional `@<version>` may be appended to specify the package version/tag to use (see the [documentation for `npm insta
I feel like the `-p` option is both very straightforward, and also hard to explain sometimes. Could you try rewording this paragraph, in general (including the bits based on what I originally wrote), and seeing if you can come up with something that conveys what it does more clearly and concisely?

2017-05-31 05:38 UTC, zkat commented on parse-args.js
> +const usage = `$0 [--package|-p <package>[@<version>]] [--cache <path>] [--save-dev|-D] [--save-prod|-P] [--save-optional|-O] [--save-bundle|-B] [--save-exact|-E] [--global|-g] [--prefix|-C] [--userc
See above comment about keeping `[@<version>]` with `<command>`, too.

2017-06-21 10:39 UTC, zkat commented
This seems to have been abandoned, so I'm closing it.

2017-06-21 10:39 UTC, closed without merging