feat(opts): add --shell-auto-fallback
zkat/npx pull request #7
Opened 2017-05-30 10:57 UTC by passcod

Generates shell code that hooks into the "command not found" mechanism
and attempts to run the command with npx instead of failing. The option
has an optional argument that forces generation of a particular variant,
otherwise it attempts to autodetect the shell. However, autodetecting is
actually very flaky, so it's better to always specify the argument.

(I don't know where you want this in the docs, so I haven't put it in.)

To use, place this in relevant shell config file:

For Bash:

    source <(npx --shell-auto-fallback bash)

For Zsh:

    source <(npx --shell-auto-fallback zsh)

For Fish:

    source (npx --shell-auto-fallback fish | psub)

As Seen On Twitter[™](https://twitter.com/passcod/status/869469928474107906)

2017-05-30 17:01 UTC, zkat commented
This is lovely. Do you mind adding docs about this to `README.md`?

2017-05-30 17:02 UTC, zkat requested changes
Docs, please!

2017-05-31 08:31 UTC, zkat requested changes
Ok! I actually went and reviewed the code, which I should've done in the first place. Looks good so far, with a few changes requested.

This still needs to get documented (be sure to add it to `usage` in both the README and in `parse-args`!)

2017-05-31 08:31 UTC, zkat commented on auto-fallback.js
> +  const { BASH_VERSION, SHELL, ZSH_VERSION } = process.env
We're restricted to `node@4` or latest, so was can't do destructuring assignment 😭

2017-05-31 08:31 UTC, zkat commented on index.js
> +  if (shell || shell === '') {
won't this *always* be true? `parseArgs()` defaults to `''`

2017-05-31 08:31 UTC, zkat commented on parse-args.js
> +    choices: ['', 'bash', 'fish', 'zsh'],
Why `''`?

2017-05-31 09:03 UTC, passcod commented on parse-args.js
> +    choices: ['', 'bash', 'fish', 'zsh'],
I'll re-test, but I think yargs refused to parse the option if the default wasn't in the choices. Although. Given the difficulty of figuring out the shell from a subprocess, maybe I should just remove both the autodetecting code and the default value here, and just do it based on the passed value.

2017-05-31 09:04 UTC, zkat commented on parse-args.js
> +    choices: ['', 'bash', 'fish', 'zsh'],
Just don't give it a default?

2017-05-31 09:05 UTC, passcod commented on index.js
> +  if (shell || shell === '') {
`requireArg` is `false`! So sometimes the option will return null/undefined/false/whatever yargs returns for a non-provided option. But `''` is falsy, so I do need to check.

2017-05-31 09:06 UTC, passcod commented on parse-args.js
> +    choices: ['', 'bash', 'fish', 'zsh'],
As to _why I made the default `''`_... err. I don't remember. I'll have a look at the code again in its entirety to see if I can figure it out.

2017-05-31 09:08 UTC, zkat commented on index.js
> +  if (shell || shell === '') {
doesn't having a default mean that you always get `''` if you don't provide the option, though? I'm so confused.

2017-05-31 09:46 UTC, passcod commented
Oops, I broke it. ...good reminder to add tests, I suppose. I'll do that now.

2017-05-31 11:14 UTC, passcod commented
Ok, I've fixed it, added tests, wrote documentation. I've kept the same functionality, but I can remove the autodetect / default if you want.

2017-05-31 21:47 UTC, zkat approved these changes

2017-05-31 21:48 UTC, merged